### PR TITLE
Update placement of vpc-connector details for Cloud Run Work Pool

### LINKED ISSUE #218: vpc-access-connector error in Google Cloud Run Work Pool
# Expectation / Proposal
I believe the default yaml file for the Google Cloud Run Work Pool needs to be updated in order to match googles change for the location of the vpc-access-connector annotation. The tag should be moved to the template's metadata according to: [VPC with Connectors](https://cloud.google.com/run/docs/configuring/vpc-connectors#configuring-job)

I changed the yaml file accordingly in the advanced tab which resolved the error:

```
{
  "job_configuration": {
    "command": "{{ command }}",
    "env": "{{ env }}",
    "labels": "{{ labels }}",
    "name": "{{ name }}",
    "region": "{{ region }}",
    "credentials": "{{ credentials }}",
    "job_body": {
      "apiVersion": "run.googleapis.com/v1",
      "kind": "Job",
      "metadata": {
        "name": "{{ name }}",
        "annotations": {
          "run.googleapis.com/launch-stage": "BETA"
        }
      },
      "spec": {
        "template": {
          "metadata": {
            "annotations": {
              "run.googleapis.com/vpc-access-connector": "{{ vpc_connector_name }}"
            }
          },
```

# Traceback / Example

`googleapiclient.errors.HttpError: <HttpError 400 when requesting https://northamerica-northeast2-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/bettercartanalytics/jobs?alt=json returned "metadata.annotations[run.googleapis.com/vpc-access-connector]: Annotation 'run.googleapis.com/vpc-access-connector' is not supported on resources of kind 'Service'. Supported kinds are: Revision, Execution". Details: "[{'@type': 'type.googleapis.com/google.rpc.BadRequest', 'fieldViolations': [{'field': 'metadata.annotations[run.googleapis.com/vpc-access-connector]', 'description': "Annotation 'run.googleapis.com/vpc-access-connector' is not supported on resources of kind 'Service'. Supported kinds are: Revision, Execution"}]}]">`

- [x] I would like to [help contribute](https://PrefectHQ.github.io/prefect-gcp/#contributing) a pull request to resolve this!

### PR DESCRIPTION
**Pull request by JohnLemmonMedely**
Google changed where the vpc-connector details need to be included in the API request for Cloud Run jobs. Looks like this has been fixed in the Cloud Run Job in this repo but not the work pool, so this change updates the work pool as well.

Closes #218 

### Checklist

- [x] References any related issue by including "Closes #<Issue Number>" or "Closes <Issue URL>".
  - If no issue exists and your change is not a small fix, please [create an issue](https://github.com/PrefectHQ/prefect-gcp/issues/new/choose) first.
- [ ] Includes tests or only affects documentation.
- [x] Passes `pre-commit` checks.
  - Run `pre-commit install && pre-commit run --all` locally for formatting and linting.
- [ ] Includes screenshots of documentation updates.
  - Run `mkdocs serve` view documentation locally.
- [x] Summarizes PR's changes in [CHANGELOG.md](https://github.com/PrefectHQ/prefect-gcp/blob/main/CHANGELOG.md)

### CODE REVIEW

**Comment by zzstoatzz** [comment]
hi @JohnLemmonMedely - thank you for the PR

I agree - I think you're good on this
> Do I need a unit test here?

> Will this change roll up into that work pool?
Hmm I'm not sure off the top of my head - @jakekaplan do we use this implementation for the push pool?

**Comment by jakekaplan** [comment]
This implementation is not directly used for the push pool, but I am happy to port this change over

**Comment by JohnLemmonMedely** [comment]
@zzstoatzz or @jakekaplan what needs to be done to merge this PR in?

**Comment by jakekaplan** [comment]
@JohnLemmonMedely apologies for the delayed reply! I missed your original message. I've updated and released the push pool implementation to match your implementation here. Will make sure this gets merged in tomorrow.

**Comment by JohnLemmonMedely** [comment]
@jakekaplan Thank you! I just dropped the CHANGELOG commit, it looks like it's been removed going forward?

**Pull request merged**
